### ISSUE TITLE
Analyze Opencart 2.3 and earlier versions 2.x

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/knawat-dropshipping-opencart#17]
- admin token user_token to token
- templates  .twig to .tpl
- setting/event model not found.
- 2.2+ has same events syntax for earlier version its different.
- 2.3 has different view path for front-end view files. ( and that is depends on theme.)
- In checkout/order model doen't have all methods
- `language_code` is not found in order
- need to redefine all language strings in controller

All OpenCart Versions
-----------------------
**v3**
1. 3.1.0.0alpha
2. 3.0.2.0 ( Developing module on this )
3. 3.0.1.2
4. 3.0.1.1
5. 3.0.0.0

**v2**
1. 2.3.0.2
2. 2.3.0.1
3. 2.3.0.0
4. 2.2.0.0
5. 2.1.0.2
6. 2.1.0.1
7. 2.1.0.0
8. 2.0.3.1
9. 2.0.2.0
10. 2.0.2.0
11. 2.0.1.0
12. 2.0.0.0

**v1.5**
1. 1.5.6.4
2. 1.5.6.3
3. 1.5.6.2
4. 1.5.6.1

**Comment by jayjittv** [comment]
We will start our extension support from version 2.3 as 2.2 and it's earlier version has more changes in code and  folder structure. So, we will consider version 2.2 later.
