### ISSUE TITLE
Opencart product images by URL (check free module)

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/knawat-dropshipping-opencart#18]

**Comment by iamdharmesh** [comment]
@HazemKhaled not found any module which we can use. found some paid module which is also uses OCMOD/vQMod for edit core files.

Can you please suggest.

**Comment by HazemKhaled** [comment]
So code it as part of our plugin or follow what we did in WooCommerce

**Comment by HazemKhaled** [comment]
@jayjittv Is there a way to use CDN in OpenCart? check if we can form one those extensions and use it

Check how they using images from external url

**Comment by jayjittv** [comment]
Hello @HazemKhaled ,

By default Opencart don't support CDN , There is paid module available for General CDN.
