### ISSUE TITLE
Internal Server Error alert at the time of install module.

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/knawat-dropshipping-opencart#20]
Getting Internal Server Error alert at the time of install module. Also left admin menu is not working.
![image 3](https://user-images.githubusercontent.com/10613171/43646583-e9af7b80-9752-11e8-833e-fbd99c48652f.png)

**Comment by ElGreetly** [comment]
Issue fixed by installing php-xml for dom
test on:
3.0.3.1
3.0.2.0
3.0.0.0
