### ISSUE TITLE
Write basic importer

### ISSUE THREAD

**Issue by iamdharmesh** [Knawat/knawat-dropshipping-opencart#3]

**Comment by jayjittv** [comment]
This task will not displayed in GUI , but Importer has been added and import is working

**Comment by ElGreetly** [comment]
Using 3.0.2.0v imported 60 products on the app.knawat.com then went back to my store knawat extension press run import I got after importing 20 products I got "Something went wrong during import please try again later" when press again gives same error and still stuck the same issue with the translated Arabic version 
![screenshot from 2019-02-04 16-24-07](https://i.ibb.co/ZdhZJVr/Screenshot-from-2019-02-04-16-24-07.png)
