### ISSUE TITLE
product with zero quantity should not be imported

### ISSUE THREAD

**Issue by jayjittv** [Knawat/knawat-dropshipping-opencart#30]
- [x] If the product already created should make it out of stock
- [x] If new product, don't create it

**Comment by ElGreetly** [comment]
If new product doesn't create it and give a reason with SKU then delete it from knawat imported list

**Comment by ElGreetly** [comment]
If already created products with sizes if all sizes not available must give out of stock

**Comment by jayjittv** [comment]
Hello @ElGreetly ,

I have changed status of product to 'out of stock' if size is not available

**Comment by ElGreetly** [comment]
out of stock appears for products imported with 0 quantity which must not be imported, but still the order out of stock issue

**Comment by ElGreetly** [comment]
my last comment is on #40 the other fixed
