### ISSUE TITLE
create endpoint for product cronjob

### ISSUE THREAD

**Issue by jayjittv** [Knawat/knawat-dropshipping-opencart#31]
Acceptance Criteria:

- [x] Create endpoint to trigger import products and sync orders
- [x] On installation, create a unique key as a token for this URL
- [x] Save last date this endpoint triggered
- [x] if the endpoint not triggered for 3 hours, show error in admin area "Knawat products not syncing, you need to setup your cronjob (how to page link) or trigger it manually from here. (link to extension admin)"
- [x] Update installation guide with this url

**Comment by ElGreetly** [comment]
http://www.domain.com?route=extension/module/knawat_cron/importProducts&access_token=3RMlbY6wsN
this url must be 
http://greetly.dev123.knawat.io/?route=extension/module/knawat_cron/importProducts&access_token=3RMlbY6wsN
need to add / before ?

**Comment by ElGreetly** [comment]
http://www.domain.com?route=extension/module/knawat_cron/importProducts&access_token=3RMlbY6wsN
this url must be
http://www.domain.com/?route=extension/module/knawat_cron/importProducts&access_token=3RMlbY6wsN
need to add / before ?

**Comment by jayjittv** [comment]
Hello  @ElGreetly ,

Url is proper and its according to opencart structure.

**Comment by ElGreetly** [comment]
if you put this URL in any browser you will find it changes to the second automatically it may cause an error with crons

**Comment by jayjittv** [comment]
Hello @ElGreetly ,

I have updated the URL.
