### ISSUE TITLE
Can't create products in 3.0.3.x

### ISSUE THREAD

**Issue by jayjittv** [Knawat/knawat-dropshipping-opencart#34]
Duplicate entry of product_advertise_google_id for product_advertise_google 

This issue is related to OpenCart `Google Shopping` extension for version 3.0.3.x https://github.com/opencart/opencart/issues/7125

**Comment by HazemKhaled** [comment]
@jayjittv any workaround here?

**Comment by jayjittv** [comment]
Hi @HazemKhaled ,

If we will uninstall Google shopping in version 3.0.3.x and reinstalling it again then Google Shopping works fine and product creation will work

**Comment by jayjittv** [comment]
Hello @ElGreetly ,

Please check this issue because you have already tested import part and in version 3.0.3.x , if you will uninstall Google shopping and reinstall it again then product creation will work (You can test this also by creating two to three products from backend Manually if Google shopping is enabled )
