### ISSUE TITLE
When item has no size available when refresh the item page it will give the same quantity as before 

### ISSUE THREAD

**Issue by ElGreetly** [Knawat/knawat-dropshipping-opencart#40]
When an item has no size available out of stock doesn't display and when refreshing
 the item page it will give the same quantity as before 
![screenshot from 2019-02-04 10-06-41](https://i.ibb.co/7NnjF4W/Screenshot-from-2019-02-04-10-06-41.png)

**Comment by jayjittv** [comment]
Hi @ElGreetly ,

I have fixed this , in such conditions product will be 'out of stock'
