### ISSUE TITLE
Some products are imported with images problem

### ISSUE THREAD

**Issue by ElGreetly** [Knawat/knawat-dropshipping-opencart#42]
![screenshot from 2019-02-04 16-34-31](https://user-images.githubusercontent.com/38695215/52485259-7dc51680-2bc9-11e9-8431-d43ff3624cc5.png)
![screenshot from 2019-02-04 16-34-22](https://user-images.githubusercontent.com/38695215/52485269-8289ca80-2bc9-11e9-9d65-a33ac456257e.png)
Most of the images with that issue are for providers that provide a PHP image path like this in the screenshot below
![screenshot from 2019-02-08 17-48-23](https://user-images.githubusercontent.com/38695215/52485372-c4b30c00-2bc9-11e9-9396-530df5fcdb07.png)
and not much images with normal URL path like this
![screenshot from 2019-02-08 17-51-09](https://user-images.githubusercontent.com/38695215/52485596-4b67e900-2bca-11e9-9d41-a8587b4bc4e7.png)
![screenshot from 2019-02-08 17-51-26](https://user-images.githubusercontent.com/38695215/52485601-4dca4300-2bca-11e9-8d41-ca76d5bc5d16.png)

**Comment by jayjittv** [comment]
Hello @ElGreetly ,

I have fixed this , please check.
