### ISSUE TITLE
Plugin knawat

### ISSUE THREAD

**Issue by user3010** [Knawat/knawat-dropshipping-opencart#53]
I have OpenCart 3.0.3.1 and I installed Knawat plugin. while I entered all the secret keys and press the save button, it take me to an empty page. The plugin keeps telling me that your store is not connect. Any one can help me with this issue please.

Thank you.

**Comment by esl4m** [comment]
plz make sure the admin link is /admin/
If issue still exists : please contact customer support support@knawat.com
