### ISSUE TITLE
Products with more than 10 variations give error in importing process

### ISSUE THREAD

**Issue by hamusthekiller** [Knawat/knawat-dropshipping-opencart#64]
When I try to import products that have 10 or more variants, the import process crashes and gives an error.
After deep investigation: the error here comes from the function adding variants in the import process code and it needs to be checked more.

Steps to regenerate:
1- import a product from Knawat catalog that has more than 10 variants to your store.
2- Try to activate the import process in your Knawat dropshipping extension and You will find the process failed when adding this product.

Expected:
Any product should get added without any issue.

**Comment by jayjittv** [comment]
@HazemKhaled @hamusthekiller 

I have checked this issue and performed below steps with opencart-3.0.3.6

I have selected few products with less variants and below products with more than 10 variants from knawat 

MGGDPRGZHWY704-3387 : Women's Ankle Strap White Heeled Shoes
MGGDPRMGSBSW305-3531 : Women's Gemmed Flat Shoes
MGGDPRMGSBSW304-3530 : Women's Ankle Strap Espadrille Shoes
MGGDPRMGSNDT04-3582 : Women's Summer Leather Sandals

I have started import process from opencart backend menu and all products has been imported including with more variants

Also, product's variants has been properly set and i am able to add that to cart from opencart frontend 

I have attached reference screenshots , please let me know if more information required for this

Can you please check or else provide more steps to regenrate this issue 
![opencart_front_import_process](https://user-images.githubusercontent.com/45030198/97670852-248fcb80-1aad-11eb-924d-3589b3589de5.png)
![opencart_front_product](https://user-images.githubusercontent.com/45030198/97670890-370a0500-1aad-11eb-8446-78f66a77db2a.png)

![knawat_products_variants](https://user-images.githubusercontent.com/45030198/97670832-193ca000-1aad-11eb-8138-d9a09d17082b.png)
