### ISSUE TITLE
Knawat extension is not compatible with 2.3.0.2 Opencart version

### ISSUE THREAD

**Issue by HeshamIsmail** [Knawat/knawat-dropshipping-opencart#82]
**Describe the bug**
When we try to upload Knawat extension to Opencart 2.3.0.2, we get error message "Unable to upload extension" or"Syntax error unexpected token" 

**To Reproduce**

1. Go to Extensions installer
2. Click on upload 
3-Add Knawat extension 1.0.9

**Expected behavior**
Knawat extension uploaded successfully

Current behavior:

We get the error message "Unable to upload extension" or"Syntax error unexpected token" or the extension doesn't appear in the extension list under "modules" 

**Screenshots**

**Enviroment (please complete the following information):**
 - OS: Windows
 - Browser Edge
 - OpenCart Version 2.3.0.2
 - Plugin Version 1.0.9,1.0.8,1.0.7

**Additional context**
I tested all extension versions till 1.0.5 with the same behavior 

**### Opencart support** advised that our extension is using twig extension which is not supported by 2.3.0.2

https://www.loom.com/share/4ff5409b5ce141c4a52ae7fd8e53c9d9

![image](https://user-images.githubusercontent.com/74185849/102994662-88c09000-4530-11eb-90fa-f2fdc1e54d41.png)

**Comment by HazemKhaled** [comment]
It's a permission error in your local setup

**Comment by HeshamIsmail** [comment]
The error message appearing on the customer website was different than the one I got on the localhost

![image](https://user-images.githubusercontent.com/74185849/103193617-09dfa480-48ee-11eb-8c07-f32862431534.png)

**Opencart support** advised that our extension is using twig extension which is not supported by 2.3.0.2

**Comment by ahmaddhridh** [comment]
Did you find the solution for that
I am facing the same problem

**Comment by HeshamIsmail** [comment]
Hello @ahmaddhridh ,

This error was resolved as soon as we properly configured FTP.
FTP on Opencart should be connected to the FTP server by username, password, and port.
FTP should have all permissions to be able to upload our Extension.

Some of our customers who had the same error above used the Twig manager extension and succeeded to upload and use our latest version successfully.
Kindly note that the Twig manager extension is not supported by Knawat. 
 
Thank you,
Hesham Ismail
